name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      # Verify requirements.txt exists
      - name: Check requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found"
            exit 1
          fi

      # Verify main.py exists (adjust if your main file has a different name)
      - name: Check main.py
        run: |
          if [ ! -f main.py ]; then
            echo "Error: main.py not found"
            exit 1
          fi

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=./package -r requirements.txt

      # Create archive of dependencies
      - name: Create archive of dependencies
        run: |
          cd package
          zip -r9 ../api.zip .
        if: success()

      # Add application files to zip (assumes main.py and other files in root)
      - name: Add application files to zip
        run: |
          zip -r9 api.zip main.py
        if: success()

      # Debug zip contents (optional, for verification)
      - name: Debug zip contents
        run: unzip -l api.zip

      # Upload zip file as artifact
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      # Check out the repository (optional, but included for clarity)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Debug AWS CLI
        run: aws sts get-caller-identity
      - name: Download Lambda api.zip
        uses: actions/download-artifact@v4
        with:
          name: api
      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi12345123451245/api.zip
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fastapi --s3-bucket fastapi12345123451245 --s3-key api.zip
