name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --target=./package -r requirements.txt
        # Installs dependencies into a 'package' directory for Lambda

      # Create archive of dependencies
      - name: Create archive of dependencies
        run: |
          cd package
          zip -r9 ../api.zip .
        # Zips the dependencies from the 'package' directory

      # Add API files to zip
      - name: Add API files to zip
        run: |
          cd api
          zip -g ../api.zip -r .
        # Adds the application code to the zip

      # Upload zip file as artifact
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Install AWS CLI
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Download the zipped artifact
      - name: Download Lambda api.zip
        uses: actions/download-artifact@v4
        with:
          name: api

      # Upload to S3
      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi12345123451245/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Deploy to Lambda
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fastapi --s3-bucket fastapi12345123451245 --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
